### PR TITLE
make the reqwest client customoziable in ReqwestLoader

### PR DESCRIPTION
**Pull request by pchampin**
the goal is to allow someone to add middlewares,
for example https://crates.io/crates/http-cache-reqwest

By the way, it is recommended by the JSON-LD spec that document loaders implement some form of caching.
Just saying... ;->

### CODE REVIEW

**Comment by pchampin** [comment]
> I like the idea, but just to be sure, are we really supposed to create a new `reqwest::Client` for every query? Or recycle the same one?

That's a good point. The current proposal aimed to be as close as possible to the original design, but having a persistent `Client` object as a field of the loader looks indeed like a better idea. I will update this PR accordingly.

**Comment by timothee-haudebourg** [comment]
Sorry for the delay, I was waiting for Rust 1.77 to come out with true support for recursive `async` functions. I can finally, **finally**, remove all ugly `Box<dyn Future>` and unnecessary trait bounds. Now that its done I cleaned up a lot of things. I also took this opportunity to put all the sub-crates inside a `crate` folder. I'm sorry this will make rebasing a bit more difficult. I really want to improve the `ReqwestLoader` though.

**Comment by pchampin** [comment]
> I can finally, finally, remove all ugly Box<dyn Future> and unnecessary trait bounds.

That's nice indeed :)

> I'm sorry this will make rebasing a bit more difficult.

Do I read that you expect me to rebase this PR? :sweat_smile: 

If so, no problem, but I can't promise to do this in the near future. Also, given how much changes there has been, I think it might be easier to make a brand new PR on top of the new code...

**Comment by timothee-haudebourg** [comment]
> Do I read that you expect me to rebase this PR? 😅
I understand :smile: 

Yes at this point restarting from scratch might be easier.

**Comment by timothee-haudebourg** [comment]
By the way, if the goal is to allow a middleware, then the client type should be [reqwest_middleware::ClientWithMiddleware](https://docs.rs/reqwest-middleware/latest/reqwest_middleware/struct.ClientWithMiddleware.html#), right?

**Comment by timothee-haudebourg** [comment]
I'm making the same changes in #74

**Pull request closed without merging**
